/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'desiredDate' : [] | [string],
  'projectType' : string,
  'name' : string,
  'email' : string,
  'company' : [] | [string],
  'message' : string,
  'timestamp' : Time,
  'budgetRange' : [] | [string],
}
export interface NetworkApplication {
  'portfolioLink' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'specialties' : string,
  'location' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getContactSubmissionByEmail' : ActorMethod<[string], ContactSubmission>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getNetworkApplicationByEmail' : ActorMethod<[string], NetworkApplication>,
  'getNetworkApplications' : ActorMethod<[], Array<NetworkApplication>>,
  'submitContact' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      [] | [string],
      [] | [string],
      string,
    ],
    undefined
  >,
  'submitNetworkApplication' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];