/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'desiredDate' : IDL.Opt(IDL.Text),
  'projectType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'budgetRange' : IDL.Opt(IDL.Text),
});
export const NetworkApplication = IDL.Record({
  'portfolioLink' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'specialties' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactSubmissionByEmail' : IDL.Func(
      [IDL.Text],
      [ContactSubmission],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getNetworkApplicationByEmail' : IDL.Func(
      [IDL.Text],
      [NetworkApplication],
      ['query'],
    ),
  'getNetworkApplications' : IDL.Func(
      [],
      [IDL.Vec(NetworkApplication)],
      ['query'],
    ),
  'submitContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'submitNetworkApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'desiredDate' : IDL.Opt(IDL.Text),
    'projectType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'budgetRange' : IDL.Opt(IDL.Text),
  });
  const NetworkApplication = IDL.Record({
    'portfolioLink' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'specialties' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getContactSubmissionByEmail' : IDL.Func(
        [IDL.Text],
        [ContactSubmission],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getNetworkApplicationByEmail' : IDL.Func(
        [IDL.Text],
        [NetworkApplication],
        ['query'],
      ),
    'getNetworkApplications' : IDL.Func(
        [],
        [IDL.Vec(NetworkApplication)],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitNetworkApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };